### ISSUE TITLE
Create Self reporting of training and practice for providers

### ISSUE THREAD

**Issue by sivaadde** [iupui-soic/mHBS_tracker#11]
1. Create the required tracker data elements.
2. On reporting of the event master trainers must be notified. 
3. Must be accessible to the user always. 

<issue priority>:<prio:low>

**Comment by SherriBucher** [comment]
Hi Liz--Is this the weekly practice in terms of using the manikin to do bag-and-mask ventilation training, or is this what we were calling the Learner Registration form in mHBB?  Best, Dr. Bucher

**Comment by Ezmeyers** [comment]
Hello Dr. Bucher, from what I understand this is going to be a questionnaire to assess the usefulness of training that is self-directed (use of videos in the new app) to establish a link between outcomes and efficacy of the training app. @sivaadde is this correct? I was going to ask for clarification on this because some metrics seem like they can be collected in the system since we will have data tied to the user (view counts..)

**Comment by sivaadde** [comment]
@Ezmeyers Yes this for providers, and they would be reporting the practice using manikin in the facility which is not mandatory (voluntary) and the reporting parameters may include time spent, activities performed and so on. This should be available to all providers and on completion of the form the respective trainers should be notified.  @SherriBucher  Is it correct Dr.Bucher.

**Comment by Ezmeyers** [comment]
@sivaadde Thank you, I understand and am working on it now!

**Comment by SherriBucher** [comment]
Hi @Ezmeyers  and @sivaadde --Agreed to all above.  Liz, keep doing what you are doing and we will look over it tomorrow, if you have it ready.

In the meantime, let me expand a bit on the discussion, which we can also chat about more at tomorrow's team meeting, if you wish.

In short, we will be evaluating the ways that end-users interact with the mHBS powered by DHIS2 platform, and assessing their thoughts about the feasibility, acceptability, and usability of the system (in whole and in part) in various ways.

First, what @sivaadde refers to above is in reference to what we call "low dose, high frequency" practice with a neonatal manikin at "HBB practice corners" in a health facility, after health care providers (HCPs) have received initial HBB training via an in-person workshop.  This is voluntary. We encourage HCPs to practice at least once per week on their bag and mask ventilation skills, and further encourage them to also practice the OSCEs, with their peers, in order to receive feedback, as they are able. We will provide paper logs at the HBB corners, so that HCPs can simply log their practice there, but we will also provide them with the opportunity to log their practice efforts via the mHBS app.

Second, there are also some indicators which, I think you are correct, @Ezmeyers , will be collected from within the app itself, or from the educational video and/or VR apps with which we eventually link the mHBS powered by DHIS2 platform. Thus, metrics such as: who accesses the video/VR scenarios, when they did so, how frequently (number of times per day/week/month/year) they look at videos or VR simulation, how long they engage with (watch or participate in) each video/scenario--and, if there are "gamification elements" involved, what their performance was in regards to interacting within training scenarios.  It is my understanding that we can capture metrics such as these simply by recording and storing information associated with each user (e.g., via their unique mHBS IDs) as they maneuver around the mHBS platform. As such, we do not need to create a separate data collection form or questionnaire to capture these types of metrics.

However, @Ezmeyers, you are correct that we will also capture metrics/indicators around end-user's opinions regarding usability, feasibility, and acceptability of the HBB training initiative overall, the mHBS app overall, or for different parts of the mHBS platform--for example, we have Teacher and Learner feedback surveys to gather information about how confident people feel after they have attended an in-person HBB training course. These tools will be digitized and available within mHBS, and I think they are included under a different issue. 

In addition, we will periodically push short digital surveys to mHBS end-users regarding their satisfaction with use of the tool--this may be only 3 or so questions, which can be answered by the end-users within a few seconds.  For some grant initiatives which are currently in the pipeline, we will generate very short, digitized surveys that ask specifically about a user's experience with other aspects of the mHBS platform, such as regarding automated SMS reminders to perform LDHF training, or  users' experiences accessing and viewing educational videos and virtual reality simulations. 

The items outlined in the latter paragraph may be outside the scope of the current Summer MURI project, but I wanted to give you more information about all the different ways that we envision tracking and capturing usability metrics for mHBS powered by DHIS2.

Best, Dr. Bucher

**Comment by Ezmeyers** [comment]
@SherriBucher Thank you for all the information! It's great that the end goal would be to cover all areas of training from understanding how often self-study manikan training is done as well as app coverage so training can be looked at from multiple aspects to see where gaps may be. I have put together some questions appropriate for the self reporting (with the help of some literature I looked at) and Siva says we can discuss this tomorrow!
