### ISSUE TITLE
Problems with gradle after upgrade to Android studio 3.0.1

### ISSUE THREAD

**Issue by sunbiz** [iupui-soic/mHBS_tracker#56]
After the upgrade to Android Studio 3.0.1, we are required to upgrade gradle to 4.1 from 2.14.1. This causes a few issues with the default configuration. We need to resolve this issue:

Error:Cannot choose between the following configurations of project :ui:
  - debugApiElements
  - debugRuntimeElements
  - releaseApiElements
  - releaseRuntimeElements
All of them match the consumer attributes:
  - Configuration 'debugApiElements':
      - Found com.android.build.api.attributes.BuildTypeAttr 'debug' but wasn't required.
      - Found com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but wasn't required.
      - Found com.android.build.gradle.internal.dependency.VariantAttr 'debug' but wasn't required.
      - Found org.gradle.api.attributes.Usage 'java-api' but wasn't required.
  - Configuration 'debugRuntimeElements':
      - Found com.android.build.api.attributes.BuildTypeAttr 'debug' but wasn't required.
      - Found com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but wasn't required.
      - Found com.android.build.gradle.internal.dependency.VariantAttr 'debug' but wasn't required.
      - Found org.gradle.api.attributes.Usage 'java-runtime' but wasn't required.
  - Configuration 'releaseApiElements':
      - Found com.android.build.api.attributes.BuildTypeAttr 'release' but wasn't required.
      - Found com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but wasn't required.
      - Found com.android.build.gradle.internal.dependency.VariantAttr 'release' but wasn't required.
      - Found org.gradle.api.attributes.Usage 'java-api' but wasn't required.
  - Configuration 'releaseRuntimeElements':
      - Found com.android.build.api.attributes.BuildTypeAttr 'release' but wasn't required.
      - Found com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but wasn't required.
      - Found com.android.build.gradle.internal.dependency.VariantAttr 'release' but wasn't required.
      - Found org.gradle.api.attributes.Usage 'java-runtime' but wasn't required.

**Comment by Ezmeyers** [comment]
The fix is short if I could edit the submodules. In that case it just requires adding:

```
    dependencies{ 
    
    compile 'com.google.dagger:dagger:2.0'
    annotationProcessor 'com.google.dagger:dagger-compiler:2.0'`

    }

```
removing `'com.neenbedankt.gradle.plugins:android-apt:1.8'`  since android-apt is deprecated with the new gradle updates and changing `apt to annotationProcessor  `inside :core's build.gradle
and then adding:
  
```
 defaultConfig {
         vectorDrawables.useSupportLibrary = true
    } 

```
to :ui to take care of an issue with a drawable.

  However, I have not found a way to override deprecated features of these modules from our app alone. 
  I tried to ask on stack overflow, my question got marked as a duplicate--although I have not 
  found this specific issue brought up regarding deprecated modules themselves. I  
  am guessing for now, we will match what they are doing at DHIS and simply not update? If I find a local 
  solution, I will implement it, but for now I will just make the changes to training app on here and work on 
 other tasks. We will just have to not click update build.gradle--but hopefully we can update in the future.

**Comment by sunbiz** [comment]
My suggestion is to file an issue in the dhis2 tracker repo. And send a pull request to that repo to fix the issue.

**Comment by Ezmeyers** [comment]
I made the pull request. For now we will just continue not hitting update.

**Comment by sunbiz** [comment]
PR made to dhis2 android sdk repo - https://github.com/dhis2/dhis2-android-sdk/pull/124
@Ezmeyers can I request you to send an email to the DHIS2 devs list to notify about the problem and link to your PR to fix it?

**Comment by Ezmeyers** [comment]
Yes I can do that, I will update this issue when there are status changes as well.

**Comment by Ezmeyers** [comment]
this issue is in review

**Comment by Ezmeyers** [comment]
git submodule update --remote --merge to pull updates
