### ISSUE TITLE
OSCE A and OSCE B form re-creation

### ISSUE THREAD

**Issue by bhavaniak** [iupui-soic/mHBS_tracker#61]
@sunbiz, the forms OSCE A and OSCE B needs to be re-created as we have discussed because they seem clumsy. I will re-create them. After which, they need to be checked, how they appear in the Android app.

**Comment by shbucher** [comment]
Hello @bhavaniak, please do not reformat the OSCEs until we have a chance to talk. They are validated evaluations that have to be constructed, and administered, in a particular manner. Thanks!

On Feb 9, 2018 7:44 PM, bhavaniak <notifications@github.com> wrote:

@sunbiz<https://github.com/sunbiz>, the forms OSCE A and OSCE B needs to be re-created as we have discussed because they seem clumsy. I will re-create them. After which, they need to be checked, how they appear in the Android app.

**Comment by bhavaniak** [comment]
Definitely @shbucher
