### ISSUE TITLE
Create OSCE B for Learners

### ISSUE THREAD

**Issue by sivaadde** [iupui-soic/mHBS_tracker#7]
[OSCEs-B-HBB-2nd-Edition.pdf](https://github.com/sivaadde/custom_dhis2_tracker/files/959808/OSCEs-B-HBB-2nd-Edition.pdf)

1. Create 23 data elements with “yes only” option check boxes.
2. Create an appropriate program with these questions made available after training. 
3. Should be able to generate score.
4. Create 5 text box questions to reflect participant performance

**Comment by Ezmeyers** [comment]
OSCEB has been created. Currently working on figuring out the best way to encoporate instructions. Sections will be used if necessary, but not ideal.

@tchilders95  The appearance of program stages are showing up in the wrong order for me, can you confirm this? If so, we will need to figure out the issue

**Comment by Ezmeyers** [comment]
We can include prompts using validation rules, which I think makes it easier for the person filling out the form. In order to include them I deleted the sections, but now there is a glitch where sections are still showing up for me even after syncing and deleting local data and logging back in. Hopefully it's just on my device.
